# T14 Hyprland monitor configuration.
# Monitor layout and workspace rules are managed externally by
# HyprDynamicMonitors (HDM) via UPower lid events + Hyprland IPC.
# Static profiles + hyprconfigs live under hosts/t14/hdm/.
# The source directive below points Hyprland at HDM's autogenerated output.
{ config, ... }:

{
  wayland.windowManager.hyprland.settings = {
    # Explicit GDK_SCALE=1 to prevent GTK apps from using default scaling.
    # The T14 panel is 1920x1080 @ 1x — no HiDPI scaling needed.
    env = [ "GDK_SCALE,1" ];
  };

  wayland.windowManager.hyprland.extraConfig = ''
    source = ${config.home.homeDirectory}/.config/hypr/monitors.conf
  '';
}
