monitor = desc:AOC 24P1W1 OTNQ4HA000101,1920x1080@60,0x0,1,transform,1
monitor = desc:Lenovo Group Limited LEN G24-10 U5B4GWF1,1920x1080@60,1080x0,1
monitor = desc:AOC 2470W GGZM3HA438259,1920x1080@60,3000x0,1
monitor = eDP-1,preferred,-30000x0,1

workspace = 1,monitor:desc:AOC 24P1W1 OTNQ4HA000101,default:true,persistent:true
workspace = 4,monitor:desc:AOC 24P1W1 OTNQ4HA000101,persistent:true
workspace = 7,monitor:desc:AOC 24P1W1 OTNQ4HA000101,persistent:true
workspace = 10,monitor:desc:AOC 24P1W1 OTNQ4HA000101
workspace = 13,monitor:desc:AOC 24P1W1 OTNQ4HA000101
workspace = 16,monitor:desc:AOC 24P1W1 OTNQ4HA000101
workspace = 19,monitor:desc:AOC 24P1W1 OTNQ4HA000101

workspace = 2,monitor:desc:Lenovo Group Limited LEN G24-10 U5B4GWF1,default:true,persistent:true
workspace = 5,monitor:desc:Lenovo Group Limited LEN G24-10 U5B4GWF1,persistent:true
workspace = 8,monitor:desc:Lenovo Group Limited LEN G24-10 U5B4GWF1,persistent:true
workspace = 11,monitor:desc:Lenovo Group Limited LEN G24-10 U5B4GWF1
workspace = 14,monitor:desc:Lenovo Group Limited LEN G24-10 U5B4GWF1
workspace = 17,monitor:desc:Lenovo Group Limited LEN G24-10 U5B4GWF1
workspace = 20,monitor:desc:Lenovo Group Limited LEN G24-10 U5B4GWF1

workspace = 3,monitor:desc:AOC 2470W GGZM3HA438259,default:true,persistent:true
workspace = 6,monitor:desc:AOC 2470W GGZM3HA438259,persistent:true
workspace = 9,monitor:desc:AOC 2470W GGZM3HA438259
workspace = 12,monitor:desc:AOC 2470W GGZM3HA438259
workspace = 15,monitor:desc:AOC 2470W GGZM3HA438259
workspace = 18,monitor:desc:AOC 2470W GGZM3HA438259
