name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Sync NixOS configs
        run: nix run nixd#nixd -- --update-nixd-flake-config || true

      - name: Run flake check
        run: nix flake check --show-trace

  build-rog:
    needs: flake-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build rog configuration
        run: nix build .#nixosConfigurations.rog.config.system.build.toplevel
        continue-on-error: true

  build-thinkcentre:
    needs: flake-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build thinkcentre configuration
        run: nix build .#nixosConfigurations.thinkcentre.config.system.build.toplevel
        continue-on-error: true
